version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`taofiqkolawole.net`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    build: ./backend
    container_name: backend
    networks:
      - web
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`taofiqkolawole.net`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
  
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=devops123
      - POSTGRES_DB=app
    networks:
      - web
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: adminer
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`db.taofiqkolawole.net`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
  
  traefik:
    image: traefik:v2.5
    container_name: traefik      